export const story = {
  prologue: [
    "Hubo una versión de mí que existía antes de conocerte.",
    "Una versión que tenía sus propios días, sus propias preocupaciones, sus propios planes y una vida que, aunque no estaba completa, parecía estarlo.",
    "Yo seguía adelante sin imaginar que, en algún lugar de esa misma historia, había una persona que todavía no conocía y que algún día conseguiría cambiar la forma en la que veo mis días.",
    "Porque a veces pensamos que las historias importantes comienzan cuando dos personas se conocen. Pero quizás no.",
    "Quizás comienzan cuando dos caminos empiezan a acercarse sin que ninguno de los dos lo sepa.",
  ],
  looks: [
    "No sé exactamente cuál fue la primera vez que te vi.",
    "Pero sí recuerdo algo.",
    "Nos mirábamos.",
    "Una mirada.",
    "Una sonrisa.",
    "Y después otra. Y otra.",
    "Como si, sin decir absolutamente nada, hubiera una conversación que solamente nosotros dos podíamos entender.",
    "No sabía tu historia. No sabía tus sueños. Solo sabía que cada vez que nuestras miradas se encontraban… algo se sentía diferente.",
    "Había algo. Una pequeña chispa.",
    "Y quizás por eso un día decidí dejar de preguntarme qué habría pasado…",
    "Me acerqué. Te hablé. Y te pedí tu número.",
    "Aunque, para ser completamente sincero… creo que mis nervios hablaron mucho antes que yo.",
  ],
  almost: [
    "Hablamos durante dos días. Solo dos.",
    "Pero a veces no hace falta demasiado tiempo para que alguien empiece a importarte.",
    "Hasta que llegó aquel mensaje.",
    "Me dijiste que habías empezado a hablar con alguien más. Y que, siendo fiel a tus valores, no querías estar hablando con dos personas al mismo tiempo.",
    "Y aunque me dolió… entendí.",
    "No intenté convencerte. Solamente te dije algo que, quizás sin saberlo, sería importante para nuestra historia:",
    "“Tienes que perseguir aquello que te haga feliz.”",
    "Después seguimos trabajando en el mismo lugar. Y de repente, aquellas miradas que antes nos hacían sonreír… se volvieron incómodas.",
    "El tiempo pasó. Un mes. Otro. Y otro. Hasta convertirse en años.",
    "Dos años sin hablar. Dos años sin saber realmente qué había sido de nosotros.",
    "Y entonces llegó un día. Un día cualquiera.",
  ],
  return: [
    "Era tu cumpleaños.",
    "Yo estaba hablando con tu mamá, como alguna vez había hecho de vez en cuando. Y aquel día me contó que era tu cumpleaños.",
    "Pensé en escribirte. Pero dudé. Después de tanto tiempo… ¿qué iba a pensar?",
    "Pero tu mamá me dijo algo. Que mi mensaje te haría bien.",
    "Así que volví a hacer algo que ya había hecho años atrás. Me armé de valor.",
    "Y te escribí.",
    "Un mensaje sencillo. Bonito. Con el único deseo de que estuvieras bien.",
    "Contestaste.",
    "Y hablamos. Y hablamos al día siguiente. Y al otro. Y al otro.",
    "Y desde aquel 2 de junio… no hemos dejado de hacerlo.",
    "Es como si esos dos años hubieran sido solamente una pausa.",
    "Y esta vez… para quedarse.",
  ],
  us: [
    "Y ahora estamos aquí. Tú y yo. Después de todo.",
    "Después de las miradas. Después del miedo. Después del tiempo. Después de habernos perdido. Después de habernos vuelto a encontrar.",
    "Y quizás esa sea mi parte favorita de nuestra historia.",
    "Que no se siente perfecta. Se siente nuestra.",
    "Me gustan nuestras conversaciones. Tus mensajes de la mañana. Nuestras noches de videollamada.",
    "Me gusta escucharte. Me gusta verte sonreír. Me gusta descubrir poco a poco cada parte de ti.",
    "Eres una niña increíblemente hermosa.",
    "Pero incluso todo eso se queda pequeño cuando pienso en tu corazón.",
    "Porque lo que más me enamora de ti no es solamente lo que veo. Es quién eres.",
    "Y no sé exactamente qué nos tiene preparado la vida. Pero sí sé que quiero descubrirlo contigo.",
  ],
  future: [
    "Dicen que el tiempo cuenta las historias. Pero yo creo que algunas historias no se miden por el tiempo.",
    "Se miden por todo lo que una persona consigue hacerte sentir.",
    "No sé cuántas noches nos quedan por compartir. No sé cuántos mensajes de buenos días. No sé cuántas citas.",
    "Pero hay algo que sí sé.",
    "Quiero estar ahí.",
    "Quiero vivir esos momentos contigo. Seguir conociéndote. Seguir haciéndote reír. Seguir creando recuerdos.",
    "Porque quizás el destino no se equivocó. Quizás simplemente sabía que todavía no era nuestro momento.",
    "Y si Dios decidió volver a cruzar nuestros caminos… yo quiero cuidar este camino.",
    "Quiero cuidarte. Quiero quererte. Y quiero seguir escribiendo esta historia contigo.",
    "Porque esta página tiene un final. Pero nuestra historia… todavía no.",
    "Feliz primer mes, mi niña. Gracias por llegar a mi vida. Y gracias por quedarte.",
    "Te quiero.",
  ],
};
